Repository utarwyn/storybook-branch-switcher, pull requests merged in 2024-10, with the labels that each got.

#8 Adding GitLab provider
  README.md
  src/cli.ts
  src/run/providers/gitlab-merge-requests.spec.ts
  src/run/providers/gitlab-merge-requests.ts
  src/run/providers/index.ts
Labels: enhancement

#10 Bump Storybook from 7.6.7 to 8.3.5
  .github/workflows/build.yml
  .storybook/preview.ts
  manager.js
  package-lock.json
  package.json
  scripts/prepublish-checks.mjs
  src/components/branch-switcher.tsx
  src/manager.spec.ts
  src/manager.tsx
  src/preview.ts
  src/stories/Introduction.mdx
  tsup.config.ts
  vitest.config.ts
Labels: minor, release, dependencies

#12 Fix CLI
  package.json
Labels: bug, patch, release

#16 Add support for subpaths
  README.md
  src/components/branch-switcher.tsx
  src/util/location.spec.ts
  src/util/location.ts
Labels: bug, patch, skip-release

#14 Added flag to checkout to update submodules when present.
  README.md
  package.json
  src/run/build.ts
Labels: enhancement, minor
